<?php

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        }
        \Illuminate\Support\Facades\DB::table('products')->truncate();
        \Illuminate\Support\Facades\DB::table('products')->insert([
            [
                'id' => 1,
                'category_id' => 1,
                'shop_id' => 1,
                'prd_code' => 'SP200801',
                'name' => 'Bàn tái chế từ bộ phận xe đạp',
                'price' => 250000,
                'thumbnail' => 'dak09nxwmdkwpkegumlf,mpfb50e7d7iac7qpekic,x5uiqqtvkqlvqbmihzl1',
                'description' => 'Dùng các bộ phận xe đạp làm mặt bàn, càng  xe có thể trở thành chiếc chân vững chắc.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'category_id' => 1,
                'shop_id' => 1,
                'prd_code' => 'SP200802',
                'name' => 'Ghế tái chế từ bộ phận xe đạp',
                'price' => 100000,
                'thumbnail' => 'juwzderyzxllbsbcyvmz,z3eics3pnlj4n0qamxn8',
                'description' => 'Bạn có một chiếc ghế đẩu độc đáo làm từ những bộ phần trên xe đạp cũ hỏng vòng xích xe đẹp, vành xe đạp.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'category_id' => 1,
                'shop_id' => 1,
                'prd_code' => 'SP200803',
                'name' => 'Móc treo làm bằng vành xe đạp',
                'price' => 50000,
                'thumbnail' => 'toi9ycfv8b2ahrgztqnv,gejlwsww3qu4iwkcysp5,hiah1axcabz22j7aysxu',
                'description' => 'Vành xe đạp tre trên trần nhà hoặc có thể gắn thêm cây trụ để biến nó thành móc treo',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-10)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'category_id' => 1,
                'shop_id' => 1,
                'prd_code' => 'SP200804',
                'name' => 'Đèn chùm được làm từ những chiếc xích xe đạp.',
                'price' => 200000,
                'thumbnail' => 'gzgjiccadmcck1zbehfa,vqtvqridbrvkdnt266bc,lbbsfiyybg3nmuqybcga',
                'description' => 'Những chiếc đèn chùm đắt tiền có thể được thay thế bằng đèn làm từ… xích xe đạp.
                Nhưng trông chúng cũng xa hoa cũng chẳng kém gì đèn mua ở cửa hiệu. ',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'category_id' => 1,
                'shop_id' => 1,
                'prd_code' => 'SP200805',
                'name' => 'Con cú trang trí làm bằng vỏ lon bia.',
                'price' => 100000,
                'thumbnail' => 'fsoyecrmd1bgbll5p2sy,jte7qmsenee5xpgomand,jbr7soewsm8lleztqiyx',
                'description' => 'Những chiếc vỏ lon bia cắt ra và tạo thành một con chim cứ.
                Khá đẹp mắt để dùng làm đồ vật trang trí bàn làm việc hoặc trong các tiệm cà phê.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'category_id' => 1,
                'shop_id' => 3,
                'prd_code' => 'SP200806',
                'name' => 'Robot trang trí làm bằng vật liệu kim loại.',
                'price' => 100000,
                'thumbnail' => 'dww6bdouioewubqne77n,lkt5fwwny8x1e60qxemi,tzabwkrvir0re5fry40a',
                'description' => 'Những chiếc vỏ lon bia nắp chai bia thìa dĩa tạo thành một chú Robot.
                Dùng để làm đồ vật trang trí cho không gian thêm sáng tạo.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'category_id' => 1,
                'shop_id' => 2,
                'prd_code' => 'SP200807',
                'name' => 'Xe mô-tô tạo từ phế liệu kim loại.',
                'price' => 300000,
                'thumbnail' => 'bzve0tvb9tpvsja3pxn8,lugulejceo6hnxjqxulu,bvoidfw5glayuizyyhzj',
                'description' => 'Những miếng sắt phế liệu bỗng thành hình chiếc mô-tô mi ni có sức hấp dẫn đặc biệt.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-9)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'category_id' => 1,
                'shop_id' => 2,
                'prd_code' => 'SP200808',
                'name' => 'Ghế ngồi làm bằng phế liệu kim loại.',
                'price' => 300000,
                'thumbnail' => 'hbr1qvqkpjo3pmfoe4lb,dsqwejb1j99xpl5mmbhj,ft6y4tjnwdtybdo7lphm',
                'description' => 'Những thùng phi sắt phế liệu cắt dưới bàn tay của những nghệ nhân thành những chiếc ghế ngồi nhiều màu sắc.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'category_id' => 1,
                'shop_id' => 2,
                'prd_code' => 'SP2008081',
                'name' => 'Bàn ghế làm bằng phế liệu kim loại.',
                'price' => 400000,
                'thumbnail' => 'tdgjefk9skizdz9pmoe9,jqr6faxnleofg4nfgahb,ueinqsikdtq6lcnh9mjb',
                'description' => 'Những chiếc bàn ghế làm bằng những sợi xịch xe trông rất độc đáo.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'category_id' => 1,
                'shop_id' => 3,
                'prd_code' => 'SP200809',
                'name' => 'Đĩa làm bằng các nắp chai bia.',
                'price' => 50000,
                'thumbnail' => 'c8zq3vxpi9amfz133z9t,bfq5ktocharxr8udplva',
                'description' => 'Đĩa đựng bánh kẹo hoa quả làm bằng những vỏ nắp chai bia trông thật đẹp mắt mà vẫn giữ được những nét mộc mạc.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-8)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 11,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008011',
                'name' => 'Kệ giày bằng gỗ pallet',
                'price' => 100000,
                'thumbnail' => 'uaaqmvnwuilq9wze6bnz,qph1kjtomiqreufvl70v,ze52ixefwtrtqzybq8ys',
                'description' => 'Giá để giày dép làm bằng gỗ pallet sẽ giúp bạn cất giữ được nhiều giáy dép hơn, đồng thời giúp giày dép luôn được thoáng khí.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 12,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008012',
                'name' => 'Bàn gấp làm bằng gỗ pallet',
                'price' => 200000,
                'thumbnail' => 'qzch8siturqsrtu1bgcu,a0pvdznqh1yh7tb09m0n',
                'description' => 'Bàn gấp làm bằng gỗ pallet tái chế.
                Tô điểm cho nội thất một cách sáng tạo để tăng sức hấp dẫn của nó tiện lợi nêu muốn làm tăng diện tích phòng ốc.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 13,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008013',
                'name' => 'Tranh treo tường làm bằng gỗ',
                'price' => 500000,
                'thumbnail' => 'm3jqjhuk2bupdn8tew6e,oiirkqqafookd4kdfcwm',
                'description' => 'Ý tưởng sử pallet với nhiều mảnh nhỏ ghép thành một bức tranh treo tường không mới nhưng vẫn đủ sức cuốn hút với bất kỳ ai,
                 khi muốn tạo những mảng sắc màu đáng yêu và bắt mắt cho tường nhà.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-7)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 14,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008014',
                'name' => 'Bản đồ thế giới treo tường làm bằng gỗ',
                'price' => 500000,
                'thumbnail' => 'posq79rqhvhzav1ryrc7,h8z4a6o1bax6iusnowot,fxattudeygp92n62z6h2',
                'description' => 'Bản Đồ Gỗ Gắn tường là một trong những decor trang trí tường bằng gỗ độc đáo của nhà ở,
                văn phòng công ty hay bất kỳ địa điểm nào.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 15,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008015',
                'name' => 'Thang cũ làm kệ để đồ',
                'price' => 100000,
                'thumbnail' => 'urd542cigrlyb4vmtpij,w5xxftxodsuxfsinuvto,hjjew2vvieic6ezj0crv',
                'description' => 'Bản Đồ Gỗ Gắn tường là một trong những decor trang trí tường bằng gỗ độc đáo của nhà ở,
                văn phòng công ty hay bất kỳ địa điểm nào.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 16,
                'category_id' => 2,
                'shop_id' => 4,
                'prd_code' => 'SP2008016',
                'name' => 'Nhà mô hình làm bằng những que kem tái chế',
                'price' => 150000,
                'thumbnail' => 'l2qvm8tvtkirvz3cmxnd,cbromf0qjwuato6uoomo',
                'description' => 'Sau khi ăn những que kem trong những ngày hè nóng bức ta có thể giữ lại những
                chiếc que để tạo ra những ngôi nhà thu nhỏ để làm trang trí trong phòng thật đặc biệt',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 17,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008017',
                'name' => 'Hộp bút làm bằng những que kem tái chế',
                'price' => 50000,
                'thumbnail' => 'rjtjqt89exguwlflnm1z,rdztqsx2udbcvissnxvs,pa2o1dtedcw3swpkol82',
                'description' => 'Những hộp bút xinh sắn, dễ thương có thể dùng làm quà tặng cho bạn bè người thân.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 18,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008018',
                'name' => 'Ghế làm từ những mảnh gỗ vụn',
                'price' => 500000,
                'thumbnail' => 'tiywadkeplmyax5gktdp,jpoluuxmywjqvyjx9s3i',
                'description' => 'Những chiếc ghế làm bằng những mảnh gỗ vụn trông thật khác biệt những vẫn giữ được những nết mộc mạc.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-6)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 19,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008019',
                'name' => 'Kệ đựng rượu bằng gỗ tái chế',
                'price' => 75000,
                'thumbnail' => 'djze3g4dibazevhi8ewl,bokurcj8dzoxdpu2crsn',
                'description' => 'Kệ đựng rượu bằng những thanh gỗ tái chế cũng không phải là lựa chọn tồi để trang trí trong nhà bếp của bạn.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 20,
                'category_id' => 2,
                'shop_id' => 3,
                'prd_code' => 'SP2008020',
                'name' => 'Đèn ngủ làm bằng gỗ tái chế',
                'price' => 100000,
                'thumbnail' => 'xs3movslmfa0kihcyyo0,via3e2k1t0epyci2rvvi,g9bndedazrts045sodda',
                'description' => 'Những chiếc đèn ngủ làm bằng gỗ tái chế vô cùng đẹp mắt và mọc mạc làm tôn vẻ đẹp trong phòng ngủ của bạn.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 21,
                'category_id' => 3,
                'shop_id' => 4,
                'prd_code' => 'SP2008021',
                'name' => 'Ghế làm bằng những chai nhựa',
                'price' => 100000,
                'thumbnail' => 'uczkdg5qbbre1dx78obn,ikhbwzn1zucccvgutoqn,t7xelxq1yutmqm4hm7rj',
                'description' => 'Bạn vẫn thường vứt bỏ vỏ chai nhựa mà không hề biết rằng chúng có thể được tái chế thành những chiếc bàn ghế đẹp, tiện dụng và độc đáo như thế này.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 22,
                'category_id' => 3,
                'shop_id' => 4,
                'prd_code' => 'SP2008022',
                'name' => 'Cốc, bát làm bằng những túi ni lông',
                'price' => 20000,
                'thumbnail' => 'kkdkfikbgpqmaoj8rvnq,q0xtrmgyebkbxfys0loc,d7oar9bbbu3m40plmlkn',
                'description' => 'Cốc và bát làm bắng túi li nông nhiều màu sắc sẽ tô điểm góc trang trí trong căn phòng của bản',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-5)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 23,
                'category_id' => 3,
                'shop_id' => 4,
                'prd_code' => 'SP2008023',
                'name' => 'Tranh làm từ nhựa tái chế',
                'price' => 200000,
                'thumbnail' => 'oxcaixvk8f9gkvkdgxme,h5djjj51rx2cubh6bsmr,ahwzbkz8orxh3ye6hkd6',
                'description' => 'Tranh trang trí làm bằng nhựa tái chế bất đặc biệt và mới mẻ.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 24,
                'category_id' => 3,
                'shop_id' => 5,
                'prd_code' => 'SP2008024',
                'name' => 'Túi sách bằng những túi ni lông',
                'price' => 100000,
                'thumbnail' => 'f5wdzfjrv4sokhylkkp3,a8xqxsgtky4mhje4dxcs,us7xqykahcaw5nmzdgvv',
                'description' => 'Túi sách làm bằng những túi ni lông không dùng đến có tính thảm mĩ, nhiều màu sắc vừa bảo vệ môi trường vừa làm sản phẩm tái chế.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 25,
                'category_id' => 3,
                'shop_id' => 5,
                'prd_code' => 'SP2008025',
                'name' => 'Bàn cà phê làm bằng nhữ chiếc lốp ô tô cũ',
                'price' => 200000,
                'thumbnail' => 'bt3xbuph0fnbbx0kgaul,tp2yateqhkwx7sviupyo,ipqwthh8z9gvtrkvcjxg',
                'description' => 'Những chiếc lốp xe ô tô cũ dưới bàn tay của nghệ nhân đã tạo những cái bàn cà phê vô cùng sinh sắn',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 26,
                'category_id' => 3,
                'shop_id' => 5,
                'prd_code' => 'SP2008026',
                'name' => 'Ghế boong làm từ lóp xe ô tô cũ',
                'price' => 300000,
                'thumbnail' => 'lnmoluz89t1hbdljgwrx,m5x8wvujbkpskhwvcic4',
                'description' => 'Những chiếc lốp xe ô tô cũ dưới bàn tay của nghệ nhân đã tạo những chiếc ghế boong vô cùng đẹp',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 27,
                'category_id' => 3,
                'shop_id' => 6,
                'prd_code' => 'SP2008027',
                'name' => 'Lọ làm bàng nhựa tái chế',
                'price' => 20000,
                'thumbnail' => 'lkiou7z7x3yktrcgdlpi,qogfdvbiic7rq4votfpq,ew1hrtk1zkzgn8kkrk1o',
                'description' => 'Những chiếc lọ được làm từ nhựa tái chế mang nhiều màu sắc sẽ là vật dụng trang trí tốt cho căn phòng của bạn.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 28,
                'category_id' => 3,
                'shop_id' => 6,
                'prd_code' => 'SP2008028',
                'name' => 'Bảng kẹp giấy làm bằng nhựa tái chế',
                'price' => 20000,
                'thumbnail' => 'lgvywkuxlvj9bhbsuc2f,zo2cuqgtnvtkponfghnl',
                'description' => 'Bảng kẹp giấy làm bằng nhưa tái chế là vật dụng hữu ích đối với học sinh, sinh viên, công việc văn phòng để lưu giữ hồ sơ.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-4)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 29,
                'category_id' => 3,
                'shop_id' => 6,
                'prd_code' => 'SP2008029',
                'name' => 'Ghế trẻ em bằng nhựa tái chế',
                'price' => 100000,
                'thumbnail' => 'zpaoltnptbgxfzgr42el,vpvokmjzgc5mahvpvwtp',
                'description' => 'Ghế dựa trẻ em được thiết kế với màu sắc đa dạng và bắt mắt, có chiều cao phù hợp, tạo tư thế ngồi thoải mái cho bé.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 30,
                'category_id' => 3,
                'shop_id' => 6,
                'prd_code' => 'SP2008030',
                'name' => 'Đĩa ăn làm từ nhựa tái chế',
                'price' => 20000,
                'thumbnail' => 'kmpfoppqsjxlkkfdmlij,e9cu9n7nicmvmgtkknkv,phjdh39lxzuhv4frlmsy',
                'description' => 'Đĩa đồ ăn, màu sắc, kiểu dáng đẹp mắt. Chất liệu an toàn, ko bay mầu khi đựng đồ ăn nóng.
                Màu sắc đa dạng, khi để hoa quả, đồ ăn tạo cảm giác ấm áp, vui vẻ khi dùng bữa...',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-3)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 31,
                'category_id' => 4,
                'shop_id' => 7,
                'prd_code' => 'SP2008031',
                'name' => 'Bóng đèn từ chai thủy tinh',
                'price' => 100000,
                'thumbnail' => 'mbvbo1lhe8e94uns9lix,m7dtfvg7bjaj9ywqtozl,engoso7bcuawinwnpdqd',
                'description' => 'Đĩa đồ ăn, màu sắc, kiểu dáng đẹp mắt. Chất liệu an toàn, ko bay mầu khi đựng đồ ăn nóng.
                Màu sắc đa dạng, khi để hoa quả, đồ ăn tạo cảm giác ấm áp, vui vẻ khi dùng bữa...',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 32,
                'category_id' => 4,
                'shop_id' => 8,
                'prd_code' => 'SP2008032',
                'name' => 'Bóng đèn từ chai rượu thủy tinh',
                'price' => 150000,
                'thumbnail' => 'fljdqe0aib0ocdgre7ic,viyvxecvpwsqjk7azpfr,jmodqnz3naiqbot1uqpl',
                'description' => 'Với thiết kế như những chai rượu ngoại, được làm từ chất liệu thủy tinh trong suốt, cao cấp,
                mẫu đèn thủy tinh hình chai rượu đã làm hài lòng rất nhiều người sử dụng.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 33,
                'category_id' => 4,
                'shop_id' => 8,
                'prd_code' => 'SP2008033',
                'name' => 'Đèn chùm làm từ thủy tinh tái chế',
                'price' => 1000000,
                'thumbnail' => 'qzpf1qtdv3jur6azooul,o8aeoyffoxatg4mpmjxd,buyouttbibfstilylr9w',
                'description' => 'Màu sắc rực rỡ phong phú tuyệt đẹp làm cho sản phẩm trở nên rất đặc biệt.
                Hoàn hỏa trang trí cho một căn phòng, đặc biết được làm từ 100% thủy tinh tái chế, mỗi mặt của đèn được làm bằng tay rất cầu kì.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 34,
                'category_id' => 4,
                'shop_id' => 8,
                'prd_code' => 'SP2008034',
                'name' => 'Bộ bàn ghế làm từ thủy tinh tái chế',
                'price' => 2000000,
                'thumbnail' => 'rxdmeavxl0lm3inyvblz,r6kb5iegfzqtlje7xtuy,ljlcrt9qth6r0shnpt6j',
                'description' => 'Bộ bàn ghế trong vườn hoặc ngoài hiên độc đáo.
                Các khối thủy tinh tái chế được đúc thủ công, sắp xếp một cách đáng yêu theo kiểu dáng độc đáo và được liên kết trong xi măng.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-2)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 35,
                'category_id' => 4,
                'shop_id' => 8,
                'prd_code' => 'SP2008035',
                'name' => 'Tranh làm từ thủy tinh tái chế',
                'price' => 1000000,
                'thumbnail' => 'm4uuk2tpifzidzt3kg9h,jkno585yer4ghseyunu1,kap7g3qgtsivvd4ntbio',
                'description' => 'Các khối thủy tinh tái chế được làm thủ công,
                sắp xếp một cách đáng yêu theo kiểu dáng độc đáo và được liên kết trong xi măng.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 36,
                'category_id' => 4,
                'shop_id' => 8,
                'prd_code' => 'SP2008036',
                'name' => 'Ghế dài làm từ thủy tinh tái chế',
                'price' => 1000000,
                'thumbnail' => 'b5ztuxuh7t476mv1p0nf,xg3drrmaczvixubtbonh,pprvzdhgiu7nhrzueahw',
                'description' => 'Tranh treo tường được làm từ thủy tinh tái thoe phương pháp thủ công,
                được sắp xếp một cách đáng yêu theo kiểu dáng độc đáo.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 37,
                'category_id' => 4,
                'shop_id' => 8,
                'prd_code' => 'SP2008037',
                'name' => 'Chai thủy tinh điều khắc',
                'price' => 100000,
                'thumbnail' => 'cblxdninawutfltrgali,kxi9znodro6aak2igwxg,qbunqh5leq1rx4chhqxu',
                'description' => 'Chai thủy tinh bỏ đi dưới bàn thay của nghệ nhân trở thành vật phẩm trang trí mang nhiều màu sắc cho căn phòng bạn.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 38,
                'category_id' => 4,
                'shop_id' => 9,
                'prd_code' => 'SP2008038',
                'name' => 'Đĩa làm từ thủy tinh tái chế',
                'price' => 20000,
                'thumbnail' => 'cvbf0l72cgsyaglcgrlm,ygcuvisk2kqmxajhsixm,ocgqvqtdc4gwk8lhm93i',
                'description' => 'Đĩa thủy tinh làm từ thủy tinh tái chế. Với thiết kế đơn giản có thể đựng thức ăn có nhiệt độ cao. Một lựa chọn tuyệt vời trong nhà bếp nhà bạn.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 39,
                'category_id' => 4,
                'shop_id' => 9,
                'prd_code' => 'SP2008039',
                'name' => 'Chuông gió làm từ thủy tinh tái chế',
                'price' => 50000,
                'thumbnail' => 's3s8lunifra8kshzpmlg,bukwar7nvwncnwfcqkxp,vq4ztnlrofz5by6dv21f',
                'description' => 'Một chiết chuông gió đang yêu được tạo ra từ bàn tay của nghệ nhân bằng nhữa vỏ chai thủy tinh rất phù hợp để trang trí.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->addDays(-1)->format('Y-m-d H:i:s'),
            ],
            [
                'id' => 40,
                'category_id' => 5,
                'shop_id' => 10,
                'prd_code' => 'SP2008040',
                'name' => 'Ảnh chân dung làm từ sách báo',
                'price' => 350000,
                'thumbnail' => 'gguajm612ufcb7afoi0a,op3yvetmhtwku7srqbeb,qalvp2ywthvd111vhowq',
                'description' => 'Ảnh chân dùng làm từ những mẩu báo lụn.
                Dưới bàn tay của các nghệ nhân những mẩu báo vụ tạp chí không còn dùng đến đã trở thành những bức ảnh tuyệt đẹp.',
                'type' => 1,
                'sale_off' => 1,
                'status' => 1,
                'created_at' => \Illuminate\Support\Carbon::now()->format('Y-m-d H:i:s'),
                'updated_at' => \Illuminate\Support\Carbon::now()->format('Y-m-d H:i:s'),
            ],
        ]);
        if (env('DB_CONNECTION') == 'mysql') {
            \Illuminate\Support\Facades\DB::statement('SET FOREIGN_KEY_CHECKS = 1');
        }
    }
}
